# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Forge Informatics Notes
email: religionofaperturelabs@gmail.com
description: >
  Informatics notes for a programming club.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://AiryShift.github.io/ForgeInformaticsNotes" # the base hostname & protocol for your site
github_username: AiryShift

# Build settings
markdown: kramdown
